### ISSUE TITLE
"Language" option

### ISSUE THREAD

**Issue by wzl-dzl** [sudasana/armcom2#1]
Just noticed the "Language" option in the menu. Are you planning on translating the game once it is finished ? 
I'd be ready to help with a French translation, if you need it. 

Also, congrats for both ArmCom 1 and 2 !

**Comment by sudasana** [comment]
I am hoping to have all in-game text displayable in French for Alpha 1, with more languages to follow. If you take a look in languages.py you'll see the bare bones of a language system, which for now is only used in the main menu, but in the future it will define text for the entire game.

Later on, I would very much appreciate help in copy-editing my French since it is quite rusty.

Thanks!
