### ISSUE TITLE
crash on new day

### ISSUE THREAD

**Issue by Trokinos** [sudasana/armcom2#12]
Hello, thanks for that excellent game

I'm running armcom2 0.9 (19-11-19) on window 10
On the Patton campaign i'm several days in, in the britanny part of the campaign and crashed apparently when being close the end of the day during a battle , after firing on an infantry, nothing seemed different from the many battle i had so far so no idea why it crashed.

I relaunch armcom2 
I press C to continue my campaign , i notice oddly i'm on the between days debriefing screen instead on the battle map.
So after assigning skill points, i move to assign the ammo then when i continue the game just crash/close, whatever happens in the dos prompt unfortunately goes too fast and close before i can read what it's about.

As this crash now always happens from that point , i thought maybe i should report this with the saved game files :
[02crasharmcom2.zip](https://github.com/sudasana/armcom2/files/3882572/02crasharmcom2.zip)

**Comment by sudasana** [comment]
Thanks for the report - unfortunately though, because of the crash the game can't be continued from its current state. I think I've fixed the saved game so that it can be continued, but without the message from the original crash I can't identify what caused the original problem. Do you happen to remember exactly what was happening when the original crash occurred?
[armcom2_save.zip](https://github.com/sudasana/armcom2/files/3897734/armcom2_save.zip)

**Comment by sudasana** [comment]
Just an update: I finally figured out what was causing this bug, it had to do with what happened when sunset occured when the player was still in a scenario. If the player saved and then continued, the game would only go to the campaign calendar interface, and the scenario object would still exist in memory, causing problems.
