### ISSUE TITLE
Add "no ammo" warning with auto-fill at the start of the day.

### ISSUE THREAD

**Issue by YARDRL** [sudasana/armcom2#19]
There should be a warning, at least, if the player accidentally presses Enter at the start of the day, and ends up beginning it with incomplete ammo (or even no ammo whatsoever if it's the first day of the campaign) equipped. The message should be something like "Lack of ammo detected! Choose default loadout?", where "Yes" will do just that, and "No" will take the player back to that screen.

In addition, if the player's tank can only use AP ammo (i.e. Matilda during the British campaign in France), that entire screen should be skipped, since the player has no meaningful choices to make there anyway.

**Comment by Edward-O** [comment]
I noticed that if you intentionally don't load ammo at all, you get 'it takes you 15 minutes to drive to the front" instead of the usual "35", which can let you get 1-2 more map hexes in. 

I think this is only practical for like Poland/USSR/Finland, since their tanks have huge amounts of ammo or you can go entire days with only machinegun fire, while things like the French and Shermans pretty much have to reload every battle.

**Comment by sudasana** [comment]
Have added a warning if player has no ammo loaded, and if a tank's main gun only has one type of ammo available, it will be automatically fully loaded with that type and this menu will be skipped. This may need to be changed in the future, however, for tanks that have more than one gun (eg. Grant/Lee) https://github.com/sudasana/armcom2/commit/3c92e77680dbb49cfed1029bf16e6fbb7ad7288e

There's no relationship between ammo load and time to arrive at the front, I think it was just a coincidence. I imagine that loading ammo will take place before dawn, and that the battlegroup heads out at the break of dawn, so no time would be saved by not loading ammo before the day starts.
