### ISSUE TITLE
Problem with Battle of France (Germany)

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#25]
I'm just starting on the April 13 patch today

I had a crash, I think the cause was either the new French Truck's unload action.  I've done this with 3 different german tanks so far.

This new version of the game also seems to put you "1 turn ahead" when you use the Continue option from the main menu after a Crash or manual exit --- when I came back the infantry was already out of the truck, so I was not able to make a "right before crash" save file, but it's so fast to get to the point of it happening on a new file that it's not too hard to report.

The changes to Panzer 38t give both the Loader and Assitant Driver the (third) machinegun, but I think it only works when the assistant Driver uses it.

Also do all the new tanks options have 0 squad groups? although I kind of think the StuG and Panzerjager work better as enemy tanks than player tanks anyway due to needing to resupply ammo VERY frequently.

**Comment by sudasana** [comment]
Thanks very much for this - I haven't had a chance yet to test out the newest version. I've fixed these in the most recent update (https://github.com/sudasana/armcom2/commit/d3a52c257787190c0e0e2695d80e27fa936ac4e2), and will upload a new build today.

FIX: crash when unloading a unit from an enemy truck (was related to the new way that enemy nations are tracked, required because that campaign has you facing both French and British units)
FIX: Player assault guns and tank destroyers not having any squad

I think the issue you experienced was directly caused by the crash; the game is automatically saved at certain points during the scenario, and some of these come between player input, so it's possible that when you continued it was in the middle of the Enemy Action phase, and the game just continued on from there. The instances when it didn't crash again right away, the trucks had not rolled an "Unload Passengers" action, so it didn't trigger the crash.

I haven't figured out the issue with the 38t's MGs - the hull MG should only be operable by the Driver and Assisstant Driver. The Loader can operate the co-ax MG, however.

**Comment by Edward-O** [comment]
The Close Combat mechanic seems to have been replaced entirely by splitting it into "attacks with grenades for enemies and the overrun command for the player. 

Grenades are decently lethal and the enemy will do it pretty frequently which feels like a good replacement for the (more lethal but very infrequent close combat from previous versions)

The Overrun command on the other hand has some weird behavior - it seems to be partly flagged as a movement action - I've had the "vehicle stalls and cannot move further" after using and I think if I go long enough it might even be capable of bogging the tank. It gives accuracy bonus to machine guns only, and will a subtraction to firing with main gun (as if you had done normal move command), it also seems to give the target movement evasion bonus if you are being shot at by someone other than the infantry you are using it on (eg a tank a tile behind the infantry) 

The Overrun command also seems to disable target acquired bonuses and gun shield penalties (although the +50 is so big it doesn't really matter)

The overrun command is still available to tanks without machine guns at all (Stug, Panzerjager, and I think one of the old ones too somewhere) even though it can only provide negative bonuses to them.

When  the overrun command is working normally … I feel like it's OK to give the player tank a big boost against infantry in the open, but it's a little too good against infantry that are dug in or fortified - I kind of liked them being the most dangerous enemies before.

**Comment by sudasana** [comment]
Let me think about this one - probably needs to be balanced a little bit.

Edit: Ok what I think I'll change in 2.0.1:
- only tanks with 1+ machine guns will have Overrun available to them
- target units will still get dug-in or entrenched bonuses
- player units on overrun will not get any terrain bonuses if attacked (they are moving between hexes)
- any attacks on player units that come from the overrun target hex later that turn will have a point blank range bonus (to represent defenders firing at the last moment)

Hopefully what this will do will make Overrun a fair option for dealing with isolated infantry units, but make it rather risky for the player as well.

**Comment by sudasana** [comment]
I've made the above changes for 2.0.1, they still need to be tested though which I'll do sometime over the next few days. You can give it a try from the following link in the meantime:
http://www.armouredcommander.com/download/armcom2_weekly.zip

**Comment by sudasana** [comment]
All changes have now been made and incorporated into the 2.0.1 release today: https://github.com/sudasana/armcom2/commit/8cf350977a886a982b8740f837328edf8d22188c
