### ISSUE TITLE
September Campaign gets stuck on Semptember 25

### ISSUE THREAD

**Issue by Edward-O** [sudasana/armcom2#30]
Very similar to the old problem with the Canadaian campaign, it just loops the date over and over.

**Comment by sudasana** [comment]
Unfortunately there was a typo in the September Campaign campaign file - fixed now: https://github.com/sudasana/armcom2/commit/92676e15237c36d5dbbe20c593a0d7cf9e2b4db9
You can re-download version 3.0.1 from the usual download link and it will be fixed in your next campaign. You'll have to restart your current campaign though
